export enum GetUpdateVersion {
  FETCH = 'GET_UPDATE_VERSION_FETCH',
  SUCCESS = 'GET_UPDATE_VERSION_SUCCESS',
  ERROR = 'GET_UPDATE_VERSION_ERROR',
}

export enum GetGroups {
  FETCH = 'GET_GROUPS_FETCH',
  SUCCESS = 'GET_GROUPS_SUCCESS',
  ERROR = 'GET_GROUPS_ERROR',
}
